repos:
  - repo: local
    hooks:
      - id: backend-checks
        name: Run backend checks
        entry: bash -c "cd backend && ruff check . && black . && mypy src"
        language: system
        types: [python]
