"""message

Revision ID: 32dd8dae4c77
Revises: bb129ee79369
Create Date: 2025-06-19 09:49:44.363339

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd8dae4c77'
down_revision: Union[str, None] = 'bb129ee79369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facegamedata', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'facegamedata', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facegamedata', type_='foreignkey')
    op.drop_column('facegamedata', 'user_id')
    # ### end Alembic commands ###
