"""message

Revision ID: bb129ee79369
Revises: f770e37cc309
Create Date: 2025-06-19 09:34:03.256604

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb129ee79369'
down_revision: Union[str, None] = 'f770e37cc309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facegamedata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('emotion_match_times', sa.JSON(), nullable=True),
    sa.Column('emotion_incorrect_times', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facegamedata')
    # ### end Alembic commands ###
