"""message

Revision ID: cff4aaa52a07
Revises: 32dd8dae4c77
Create Date: 2025-06-19 10:24:12.341724

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff4aaa52a07'
down_revision: Union[str, None] = '32dd8dae4c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facegamedata', sa.Column('game_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facegamedata', 'game_summary')
    # ### end Alembic commands ###
